### ISSUE TITLE
Feedback about `getting-started`

### ISSUE THREAD

**Issue by joeljuca** [adopt-liveview/feedback#5]
Eu sugeriria que a instalação de Elixir/Erlang estaria fora do escopo de um curso de LiveView.

O asdf é uma ótima solução (eu uso tb), mas tem outras formas de instalar o Elixir (eg: Homebrew no macOS) que, no caso, seria mais que suficiente pra quem está aprendendo LV.

**Comment by lubien** [comment]
I've created the above issue on the main repo. Thanks for your feedback!
